const $=s=>document.querySelector(s);let current=null,currentTab='overview';
async function request(url,options={}){const r=await fetch(url,{headers:{'content-type':'application/json',...(options.headers||{})},...options});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||'Request failed');return data}
async function boot(){try{await request('/api/me');showApp()}catch{}}
async function showApp(){$('#login').hidden=true;$('#app').hidden=false;await devices()}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';try{await request('/api/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});showApp()}catch(x){$('#loginError').textContent=x.message}});
async function devices(){const {devices}=await request('/api/devices');$('#deviceList').innerHTML=devices.map(d=>`<article class="device-card" data-id="${d.id}"><div><h3>${esc(d.name)}</h3><div class="status ${d.online?'online':''}">${d.online?'Connected':'Offline'} · ${esc(d.model||'Android')}</div></div><span>›</span></article>`).join('');$('#empty').hidden=devices.length>0;$('#deviceList').hidden=false;$('#detail').hidden=true;document.querySelectorAll('.device-card').forEach(x=>x.onclick=()=>openDevice(x.dataset.id))}
async function add(){const x=await request('/api/enrollments',{method:'POST',body:'{}'});$('#token').textContent=x.token;$('#expiry').textContent=`Expires ${new Date(x.expiresAt).toLocaleTimeString()}`;$('#enrollDialog').showModal()}
$('#addDevice').onclick=add;$('#emptyAdd').onclick=add;$('.close').onclick=()=>$('#enrollDialog').close();$('#copyToken').onclick=async()=>{await navigator.clipboard.writeText($('#token').textContent);$('#copyToken').textContent='Copied ✓';setTimeout(()=>$('#copyToken').textContent='Copy token',1500)};
async function openDevice(id){current=await request(`/api/devices/${id}`);$('#deviceList').hidden=true;$('#empty').hidden=true;$('#detail').hidden=false;const d=current.device;$('#deviceHeader').innerHTML=`<div class="hero"><div><h2>${esc(d.name)}</h2><span class="status ${d.online?'online':''}">${d.online?'Connected now':'Last seen '+ago(d.lastSeenAt)}</span></div></div>`;render()}
$('#back').onclick=devices;document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{currentTab=b.dataset.tab;document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));render()});
function render(){const d=current.device,c=$('#tabContent');if(currentTab==='overview'){const s=d.scan||{};c.innerHTML=`<div class="grid"><div class="metric"><small>Android</small><strong>${esc(d.androidVersion||'—')}</strong></div><div class="metric"><small>Security patch</small><strong>${esc(s.securityPatch||'Not scanned')}</strong></div><div class="metric"><small>Encryption</small><strong>${s.encrypted===true?'Enabled':s.encrypted===false?'Review':'Not scanned'}</strong></div><div class="metric"><small>Screen lock</small><strong>${s.secureLock===true?'Enabled':s.secureLock===false?'Review':'Not scanned'}</strong></div></div><div class="panel spaced"><h3>Security assessment</h3>${d.scan?`<p>Developer options: <b>${s.developerOptions?'Enabled':'Disabled'}</b></p><p>ADB debugging: <b>${s.adbEnabled?'Enabled':'Disabled'}</b></p><p>Test build tags: <b>${s.testKeys?'Detected':'Not detected'}</b></p><p class="time">Scanned ${new Date(s.at).toLocaleString()}</p>`:'<p class="muted">Run a security scan from the Android companion.</p>'}<div class="actions"><a class="button-link" href="/api/devices/${d.id}/export">Export report</a><button class="danger" id="purge">Delete collected data</button><button class="danger" id="revoke">Revoke device</button></div></div>`;$('#revoke').onclick=async()=>{if(confirm('Disconnect and revoke this Android?')){await request(`/api/devices/${d.id}/revoke`,{method:'POST',body:'{}'});devices()}};$('#purge').onclick=async()=>{if(confirm('Delete collected notifications, selected photos, imported texts and app-audit data?')){await request(`/api/devices/${d.id}/purge`,{method:'POST',body:'{}'});await openDevice(d.id)}}}else if(currentTab==='notifications'){c.innerHTML=listPanel('New notification previews',current.notifications,n=>`<b>${esc(n.app||'Android app')}</b><p>${esc(n.title)}</p><p>${esc(n.text)}</p><span class="time">${new Date(n.at).toLocaleString()}</span>`)}else if(currentTab==='messages'){c.innerHTML=listPanel('Owner-imported message backup',current.messages,m=>`<b>${esc(m.sender||'Unknown sender')}</b><p>${esc(m.text)}</p><span class="time">${m.messageAt?new Date(m.messageAt).toLocaleString():'No date supplied'}</span>`)}else if(currentTab==='photos'){c.innerHTML=`<div class="panel"><h3>Owner-selected photos</h3>${current.photos.length?`<div class="photos">${current.photos.map(p=>`<img src="/api/photos/${p.id}" alt="${esc(p.name)}">`).join('')}</div>`:'<p class="muted">No photos have been selected and shared.</p>'}</div>`}else if(currentTab==='apps'){c.innerHTML=listPanel('Launchable application audit',current.apps,a=>`<b>${esc(a.name||a.packageName)}</b><p class="time">${esc(a.packageName)}</p>`)}else{c.innerHTML=listPanel('Activity history',current.events,e=>`<b>${esc(e.type)}</b><p>${esc(e.detail)}</p><span class="time">${new Date(e.at).toLocaleString()}</span>`)}}
function listPanel(title,items,renderItem){return `<div class="panel"><h3>${esc(title)}</h3>${items.length?items.map(x=>`<div class="item">${renderItem(x)}</div>`).join(''):'<p class="muted">Nothing has been shared yet.</p>'}</div>`}
function esc(v){return String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}function ago(t){const m=Math.floor((Date.now()-t)/60000);return m<1?'just now':m<60?`${m}m ago`:`${Math.floor(m/60)}h ago`}
boot();
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
